### ISSUE TITLE
Uncaught Error: module "libs/vendors/aruco/index" is not defined

### ISSUE THREAD

**Issue by SilverMaple** [imokya/wechat-ar#4]
你好，想问下这里缺失的文件是在哪里？

**Comment by cherry511** [comment]
> 你好，想问下这里缺失的文件是在哪里？

同问

**Comment by MachiBarton** [comment]
> > 你好，想问下这里缺失的文件是在哪里？
> 
> 同问

同问

**Comment by hen0920** [comment]
同 确实缺文件

**Comment by AnkerLeng** [comment]
Uncaught Error: module "libs/vendors/aruco/index" is not defined

**Comment by ricecakedad** [comment]
应该是这个js https://github.com/jcmellado/js-aruco/blob/master/src/aruco.js

**Comment by imokya** [comment]
没有用到这个文件，已经删除
